gamecollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
 ]

main_app/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('games/', views.games_index, name='index'),
    path('games/<int:game_id>/', views.game_detail, name='detail'),
    path('games/create/', views.GameCreate.as_view(), name='game_create'),
    path('games/<int:pk>/update/', views.GameUpdate.as_view(), name='game_update'),
    path('games/<int:pk>/delete/', views.GameDelete.as_view(), name='game_delete'),
    path('games/<int:game_id>/add_play/', views.add_play, name='add_play'),
    path('games/<int:game_id>/add_photo/', views.add_photo, name='add_photo'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

# Create your models here.

WINNER = [
    ('J', 'Jay'),
    ('M', 'Mollie'),
    ('A', 'Aja'),
    ('C', 'Calvin')
]


class Game(models.Model):
    name = models.CharField(max_length=(100))
    photos = models.CharField("Photo URL", max_length=(500))
    players = models.CharField("Player count", max_length=(50))
    description = models.TextField(max_length=(250))
    user = models.ForeignKey(User, on_delete=models.CASCADE, )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'game_id': self.id})


class Play(models.Model):
    date = models.DateField("date", default=date.today)
    winner = models.CharField(
            "winner", max_length=1, choices=WINNER, default=WINNER[0][0]
            )
    game = models.ForeignKey(Game, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_winner_display()} won on {self.date}"


class Photo(models.Model):
    url = models.CharField(max_length=200)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for game_id: {self.game_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Play
from django.urls import reverse


class PlayForm(ModelForm):
    class Meta:
        model = Play
        fields = ["date", "winner"]

    def get_absolute_url(self):
        return reverse('detail', kwargs={'game_id': self.id})

main_app/views.py
# Add the following import
# from django.http import HttpResponse
import os
import uuid
import boto3
from .forms import PlayForm
from .models import Game, Photo
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin


# Define the home view


def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')


def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid sign up - try again'
            form = UserCreationForm()
            context = {'form': form, 'error_message': error_message}
            return render(request, 'registration/signup.html', context)


@login_required
def add_photo(request, game_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + \
            photo_file.name[photo_file.name.rfind('.'):]
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(photo_file, bucket, key)
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            Photo.objects.create(url=url, game_id=game_id)
        except:
            print('An error occurred uploading file to S3')
    return redirect('detail', game_id=game_id)


@login_required
def games_index(request):
    games = Game.objects.filter(user=request.user)
    return render(request, 'games/index.html', {'games': games})


@login_required
def game_detail(request, game_id):
    game = Game.objects.get(id=game_id)
    play_form = PlayForm()
    return render(request, 'games/detail.html', {'game': game, 'play_form': play_form})


@login_required
def add_play(request, game_id):
    form = PlayForm(request.POST)
    if form.is_valid():
        new_play = form.save(commit=False)
        new_play.game_id = game_id
        new_play.save()

    return redirect('detail', game_id=game_id)


class GameCreate(LoginRequiredMixin, CreateView):
    model = Game
    fields = '__all__'
    success_url = '/games'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class GameUpdate(LoginRequiredMixin, UpdateView):
    model = Game
    fields = ['name', 'photos', 'players', 'description']


class GameDelete(LoginRequiredMixin, DeleteView):
    model = Game
    success_url = '/games/'

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Game Collector</h1>
<hr />
<p>Hi! I'm Jay Thurber, a Full Stack Developer with a passion for board games!</p>
{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Board Game Collector</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  </head>

<!-- Top navbar -->
  <body class="text-center">
    <nav class="navbar-expand-sm bg-light navbar-light d-flex align-items-center" style="font-size: 20px">
      <div class="mr-auto">
          <a class="navbar-brand" href="/"> <i class="bi bi-dice-6"> </i>Board Game Collector </a>
      </div>
      <div class="navbar-nav">
      {% if user.is_authenticated %}
      <a class="nav-link" href="{% url 'game_create' %}">Add Game</a>
      <a class="nav-link" href="{% url 'index' %}">View Collection</a>
      <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
      {% else %}
      <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
      <a class="nav-link" href="{% url 'login' %}">Log In</a>
      {% endif %}
    </div>
    </nav>
    <div class="container">
    {% block content %}
    {% endblock %}
    </div>
<!-- Bottom nabar -->
    <nav class="navbar-sm bg-dark fixed-bottom d-flex justify-content-end">
      <div class="p-1"><p style="color: white"><small>All Rights Reserved, &copy; 2021 Game Collector</small></p></div>
    </nav>
<!-- JS for Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

main_app/templates/games/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="jumbotron">
  <div>
    <img class="img-thumbnail" src="{{game.photos}}">
    <br>
  </div>
  <span class="display-4">{{ game.name }}</span>
  <p class="lead">{{ game.players }} players</p>
  <hr class="my-4">
  <p class="lead">{{ game.description }}</p>
</div>
<div class="container">
  <table class="table table-striped">
    <h1>Play History</h1>
    <thead>
      <tr>
        <th>Date</th>
        <th>Winner</th>
      </tr>
    </thead>
    <tbody>
      {% for play in game.play_set.all %}
      <tr>
        <td>{{play.date}}</td>
        <td>{{play.get_winner_display}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <form class="d-flex justify-content-around" action="{% url 'add_play' game.id%}" method="post">
    {% csrf_token %}
    {{ play_form.as_table }}
    <input type="submit" class="btn btn-green" value="Add Session" />
    <br>
  </form>
  <br>
  <div class="">
    <a class="btn btn-primary" href="{% url 'game_update' game.id %}">Edit {{game.name}}</a>
    <a class="btn btn-danger" href="{% url 'game_delete' game.id %}">Delete {{game.name}}</a>
  </div>
  <br><br><br>
  {% endblock %}

main_app/templates/games/index.html
{% extends 'base.html' %}
{% block content %}
<div class="text-center jumbotron">

  <h1>My Collection</h1>
  {% for game in games %}
  <div class="container text-center d-flex flex-column align-items-center list-group-item">
    <br>
    <a href="{% url 'detail' game.id %}">
      <img class="img-thumbnail" style="width: 50%" src="{{ game.photos }}" alt=""><br>
      {{ game.name }}
    </a>
  </div>
  <br>
  {% endfor %}
  <a class="btn btn-secondary" href="{% url 'game_create' %}">Add Game</a>

</div>
{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<div class="jumbotron">
  <h1 class="display-4">Welcome to Board Game Collector</h1>
  <p class="lead">Track your collection and play history</p>
  {% if user.is_not_authenticated %}
  <p>Please log in to begin adding games. </p>
  {% endif %}
</div>
{% endblock%}

main_app/templates/main_app/game_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<br>
<div class="jumbotron">
  <span class="display-4">Delete {{ object.name }}</span>
  <hr class="my-4">
  <p class="lead">Are you sure you want to delete {{ object.name }}?</p>
  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Delete" class="btn btn-danger">
    <a class="btn" href="{% url 'detail' game.id %}">Cancel</a>
  </form>
</div>
{% endblock %}

main_app/templates/main_app/game_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<div class="container">
  <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% endif %}
  <form class="d-flex flex-column justify-content-center jumbotron text-center" action="" method="post">
    <h1>Add Game</h1>
    {% csrf_token %}
    {{ form.as_table }}
    <input class="flex-direction-column align-self-center" type="submit" value="Submit" class="btn">
  </form>
  {% endblock %}

main_app/templates/main_app/player_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
   <h1>Edit <span>{{object.name}}</span></h1>
 {% else %}
   <h1>Add Player</h1>
 {% endif %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}